return {}
-- return {
--   "folke/zen-mode.nvim",
--   opts = {
--     -- your configuration comes here
--     -- or leave it empty to use the default settings
--     -- refer to the configuration section below
--     window = {
--       backdrop = 1, -- shade the backdrop of the Zen window. Set to 1 to keep the same as Normal
--       -- height and width can be:
--       -- * an absolute number of cells when > 1
--       -- * a percentage of the width / height of the editor when <= 1
--       -- * a function that returns the width or the height
--       width = 100,
--     },
--   },
-- }
